-- migrate_v6_patch.sql
-- 불필요 업적 8개 삭제 (점심시간 주1회 시험 환경에 맞지 않는 업적)
-- NIGHT_OWL, EARLY_BIRD, WEEKEND_WARRIOR, MIDNIGHT_EXAM, DAILY_EXAM, TRIPLE_EXAM_DAY, BEAT_EVERYONE, EXAM_STREAK

SET @ids = 'NIGHT_OWL,EARLY_BIRD,WEEKEND_WARRIOR,MIDNIGHT_EXAM,DAILY_EXAM,TRIPLE_EXAM_DAY,BEAT_EVERYONE,EXAM_STREAK';

-- 1. user_badges (BADGE_EXAM_STREAK 연결)
DELETE ub FROM user_badges ub
JOIN badges b ON ub.badge_id = b.id
WHERE b.achievement_id IN ('NIGHT_OWL','EARLY_BIRD','WEEKEND_WARRIOR','MIDNIGHT_EXAM','DAILY_EXAM','TRIPLE_EXAM_DAY','BEAT_EVERYONE','EXAM_STREAK');

-- 2. badges
DELETE FROM badges WHERE achievement_id IN ('NIGHT_OWL','EARLY_BIRD','WEEKEND_WARRIOR','MIDNIGHT_EXAM','DAILY_EXAM','TRIPLE_EXAM_DAY','BEAT_EVERYONE','EXAM_STREAK');

-- 3. achievement_progress
DELETE FROM achievement_progress WHERE achievement_id IN ('NIGHT_OWL','EARLY_BIRD','WEEKEND_WARRIOR','MIDNIGHT_EXAM','DAILY_EXAM','TRIPLE_EXAM_DAY','BEAT_EVERYONE','EXAM_STREAK');

-- 4. user_achievements
DELETE FROM user_achievements WHERE achievement_id IN ('NIGHT_OWL','EARLY_BIRD','WEEKEND_WARRIOR','MIDNIGHT_EXAM','DAILY_EXAM','TRIPLE_EXAM_DAY','BEAT_EVERYONE','EXAM_STREAK');

-- 5. achievements
DELETE FROM achievements WHERE id IN ('NIGHT_OWL','EARLY_BIRD','WEEKEND_WARRIOR','MIDNIGHT_EXAM','DAILY_EXAM','TRIPLE_EXAM_DAY','BEAT_EVERYONE','EXAM_STREAK');

-- 확인
SELECT COUNT(*) AS remaining_achievements FROM achievements;
SELECT COUNT(*) AS remaining_badges FROM badges;
